openapi: 3.0.0
info:
  title: Documentation Simple Rest API
  description: This is minimum CRUD requirement for each sample rest API who made from any language and frameworks
  version: 0.1.1
servers:
  - url: http://localhost:1818
    description: own server

paths:
  /bycycle:
    get:
      summary: return a list of bycycle brands.
      description: All bycycle will shows here.
      responses:
        200:
          description: A JSON array of bycyle brands
          content:
            application/json:
              schema:
                type: object
                properties:
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Exotic
